name: Create Pull Request

on:
  workflow_dispatch: ~
  push:
    branches:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Checkout docs-all repo
        uses: actions/checkout@v4
        with:
          repository: metaodi/docs-all
          path: docs-all
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
      - name: Update Part A files
        run: |
          tree
          ls -l docs-all
          cp -r a/* docs-all/a/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: 'Docs Update - Part A'
          body: 'Documentation update from part A'
          path: docs-all
          add-paths: a
          branch: 'docs-a-update'
          base: 'main'
          draft: false
          assignees: mchaamsler
          
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
